import type { Metadata } from 'next';
import { ThemeProvider } from '@/providers/theme-provider';
import { ModalProvider } from '@/providers/modal-provider';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

export const metadata: Metadata = {
	title: 'Shop Admin',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<ModalProvider />
					<Toaster />
					<main className="flex-1">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
